logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:./h2/oocl-agile-fs
    driver-class-name: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
    username: sa
    password:
  jpa:
    hibernate:
      ddl_auto: validate
    # create ????hibernate???????
    # create-drop ????hibernate??model????sessionFactory???????
    # update ????hibernate????????????????
    # validate ????hibernate?????????????????????????????
  #    properties.hibernate.hbm2ddl.auto: update
  #?????????? localhost:2020/h2-console
  flyway:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2